theme: jekyll-theme-hacker

title: Gui Lucena
description: Enthusiast of the best web & mobile development technologies.

show_downloads: false
# google_analytics: [Your Google Analytics tracking ID]
